---
- name: Change password for all servers (offline, no passlib)
  hosts: all
  become: yes
  vars:
    username: root
    new_password_plain: "NewP@ssw0rd!"  # Mật khẩu mới dạng text
  tasks:
    - name: Change password using chpasswd
      ansible.builtin.shell: |
        echo "{{ username }}:{{ new_password_plain }}" | chpasswd
      args:
        warn: false
      register: result

    - name: Show result
      debug:
        var: result
